schedule: "every month"
search: False
requirements:
  - requirements/default.txt:
      update: all
      pin: true
  - docs/requirements.txt:
      update: all
      pin: true
  - e2e-tests/Pipfile:
       update: all
       pin: true
  - e2e-tests/pipenv.txt:
       update: all
       pin: true
