language: python
python:
  - "2.6"

addons:
  postgresql: "9.3"

services:
  - rabbitmq
  - elasticsearch
  - memcached

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y node-less libxml2-dev libxslt1-dev

install:
  - make bootstrap

script:
  - ./scripts/build.sh
